import type { Metadata } from 'next'
import './globals.css'

import Header from '../components/header/Header'
import { AppContextProvider } from '../components/AppContext';
import Footer from '../components/footer/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppContextProvider>
          <Header />
          {children}
          <Footer />
        </AppContextProvider>
      </body>
    </html>
  )
}
