import type { Metadata } from "next"
import "./global.css"

import { ToastProvider } from "@/lib/notifications/toastify-provider"
import { LoadingProvider } from "@/modules/global/loading-provider.tsx/loading-provider"
import { StoreProvider } from "@/store/store-provider"
import { Header } from "@/modules/global/header/header"
import { AuthProvider } from "@/modules/global/auth-provider/auth-provider"
import { AntdRegistry } from "@ant-design/nextjs-registry"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const Providers = ({ children }: { children: React.ReactNode }) => {
  return (
    <StoreProvider>
      <AuthProvider>
        <AntdRegistry>
          <ToastProvider>
            <LoadingProvider>{children}</LoadingProvider>
          </ToastProvider>
        </AntdRegistry>
      </AuthProvider>
    </StoreProvider>
  )
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
