import Head from "next/head";
import styles from "./collections.module.css";
import { Inter } from "next/font/google";
import { CARDS } from "@/source/heros";
import { useState } from "react";
import { CardOverview } from "@/components/modules/card-overview/card-overview";
import { CardList } from "@/components/pages/collectionds/card-list/card-list";
import { Hero } from "@/source/hero/hero";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [cardOverviewShowItem, setCardOverviewShowItem] = useState<Hero | null>(
    null
  );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {cardOverviewShowItem && (
        <CardOverview
          card={cardOverviewShowItem}
          isShow={!!cardOverviewShowItem}
          setClose={() => setCardOverviewShowItem(null)}
        />
      )}
      <CardList
        cards={CARDS}
        setCardOverviewShowItem={setCardOverviewShowItem}
      />
    </>
  );
}
