import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { useAuth } from "@/contexts/auth-context";
import { doSignOut } from "@/utils/auth-handlers";
import { User } from "@/types";
import { Button } from "@/components/UI/button/button";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { currentUser, setCurrentUser, setUserLoggedIn } = useAuth();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>Settings</h1>
        <Button title="Sign Out" onClick={doSignOut} />
        <h5>{(currentUser as User).uid}</h5>
      </div>
    </>
  );
}
